apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: component2
  namespace: wen-vault1
  labels:
    app: component2
    env: ci2
spec:
  selector:
    matchLabels:
      app: component2 
      env: ci2
  replicas: 1 
  template:
    metadata:
      labels:
        app: component2 
        env: ci2 
    spec:
      serviceAccountName: serviceaccount-vault-admin 
      automountServiceAccountToken: true
      containers:
      - name: component1-ci2
        image: portcheck:latest
        resources:           
          limits:             
            cpu: 100m
            memory: 50Mi
