apiVersion: v1
kind: ConfigMap
metadata:
    name: configmapsecret
    namespace: NAMESPACEWEN
    data:
        config.hcl: |
        "exit_after_auth" = false
        "pid_file" = "/home/vault/.pid"
        "auto_auth" = {
      		"method" = {
        		"config" = { "role" = "NAMESPACEWEN-APPLICATIONWEN-role" }
        	  "type" = "kubernetes"
     		  }
          "sink" = {
            "config" = { "path" = "/home/vault/.token" }
             "type" = "file"
          }
        }
				"vault" = {
      		"address" = "https://vault-dev.patlunditest.svc.cluster.local:8200"
      		"ca_cert" = "/vault/tls/ca.crt"
      		"client_cert" = "/vault/tls/client.crt"
      		"client_key" = "/vault/tls/client.key"
    		}
        "template" = {
          "contents" = "{{- with secret \"NAMESPACEWEN/APPLICATONWEN\" -}}Name={{ .Data.data.username }} PSW is {{ .Data.data.password }}{{- end }}"
          "destination" = "MYCOMPANY/NAMESPACEWEN/APPLICATONWEN"
        }

